image: maven:3.5.0-jdk-8-alpine

cache:                                                                                                  
  paths:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"   

before_script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - | 
    if [[ "${TRAVIS_BRANCH}" == release-* ]]; then
        QUALIFIER=-frozen-${CI_PIPELINE_ID}
    elif [[ "${TRAVIS_BRANCH}" == "development" ]]; then
        QUALIFIER=-dev-${CI_PIPELINE_ID}
    elif [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
        QUALIFIER=""
    else
        QUALIFIER=-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
    fi && mvn build-helper:parse-version versions:set 
        -DgenerateBackupPoms=false 
        -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'${QUALIFIER}

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--settings ${HOME}/.m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Duser.home=${HOME} -Dmaven.repo.local=${HOME}/.m2/repository"
  
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify

deploy_release:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -P stage-devel-bintray deploy
  only:
    - master

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -P stage-devel-nexus deploy
