language: bash
sudo: required
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- |
  if [[ "${TRAVIS_COMMIT_MESSAGE}" == "[gitflow]"* ]] && [[ "${TRAVIS_BRANCH}" != v[0-9]* ]] && [[ "${TRAVIS_BRANCH}" != development ]] && [[ "${TRAVIS_BRANCH}" != release-* ]]; then
    travis_terminate 0
  fi
before_script:
- cp .ci-settings.xml $HOME/.m2/settings.xml
script:
- |
  if [[ "${TRAVIS_BRANCH}" == release-* ]]; then
    QUALIFIER=-frozen-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    QUALIFIER=-dev-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    QUALIFIER=""
  else
    QUALIFIER=-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  fi && ./.travis.scripts/mvn.sh build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'-travis${QUALIFIER}
- "./.travis.scripts/mvn.sh -Dmaven.site.skip=true clean verify -B -e -V"
after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]] || [[ "${TRAVIS_BRANCH}" == release-* ]] || [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    ./.travis.scripts/mvn.sh sonar:sonar
  fi
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    ./.travis.scripts/mvn.sh -P github-site site  fi
deploy:
  provider: script
  script: "./.travis.scripts/mvn.sh -Dmaven.site.skip=true -P stage-devel-bintray
    deploy"
  skip_cleanup: true
  on:
    all_branches: true
branches:
  except:
  - gh-pages
  - master
notifications:
  email:
    recipients:
    - emmanuel.bruno@univ-tln.fr
    on_success: never
    on_failure: never
  slack:
    secure: mxSioTACsN0R7yPDVNVhaxhh8/c4WUwJWd6CP2rxUTV2rP0P+NdLP24J1Pyl8zUHLhAkl4OaXA0k5lvuNFa7SygmUt8lnTm3CwzokM3H89Z3LIyi2Y1Qj+lYRkvFkyOAlqvrGt7ukN4kRKfGjaZDqSBleoWYWvY5Q0zY+OFZhutX8lNiuGpqaBQ4cUxa0rGnZxFvGoYOzDx3MwhgdJ1nP5GxTVfCpAMDXSyqGepP5o82gG5UCd0REKI7wsq93TrQgkQQ5LSfBcr9IymVvoES2JJF7V2ETRoAE9zulew08DUkVtBkgGZyXBd7T5uxkpvzigSm87D5yPuF+YxLXFLhD//MR01/uHk/Cg60StqrxKj92On9+D0got9IRQMiE3BWVQEPnLDtbvXzwJeqdSOuS7aEETN2Fq35SUZMKR19HI29rlYu6fSgqhYVvxlv2Hx8DKkrtfkuFVzDkrxhUZasZs2+7jBzR4qitvF4vSSVosNb9z4YVN1Axu0EjSo2DyLMRA6dEIVP+/T8ZbV4cI/KLAluDeC/tJ2/jkfKTxKbCO+4oq4bNnE3Ql+RUCdJnkm9gDjdSqIRBuMTbQlDuZLQ5utb5uIKG1d3TfSqwYyEzCl9dfggF0g2xTDBP7F4rq06KL5k1enVfz4u/IBN5tr1Rg2n0nl2TokKW0eIEdkME/s=
env:
  global:
  - secure: Su60HEHpztuJkdfcTQkZNamPg6pGNPNkumBAMvIZTlUr9WP4L/6TxGZLR6N1Ov8dxIvb4dxSU6vfJp76g1m6botN1KFfCiUu2ty9vciaXuz7fj8WJq71N5zEW0yBTEu4/+Xzb71QY5w0bY5dvxLl7TVmoqeacZSIQNZWaKXRPKMXVhV+b6JcsJj/uVADEY+LRGCY81Oy5KhkCL9WbNl8j0/U5f5Fvdf3eTI/3aFG7XxreidXtoTCzMvaXAUSCXTw9TC1wLzZDHFC1PkhoLkc3wiao77KrPLnaJ1NCHcA6p9BRChRI4p9v4s6OG2XkTWX4sw2f/2sPsXehCO/t9FFNzL2jeof8Xt63Z+PoYXKbpCOdGUMDROoEvHohpNhmHEGfhnMhOxxDsEG0pjxpB8B+hsnB9UWFUwLutEuh76hNrRzfB2qBYMAIylqFMZSbg8/0Hh6xQgK2aUwb4gtQxHj0NpRa7rnn5Rdu1cnMAqxUvcki7MtmzxNZbw7/a0GildmvUC74xuXSXcGLBeIE6Np4ZbvRQvb6RlgDGzQrUxvqIAjHyXBZpm6rrp4vHuedzoQXZFCiX0mi1hBWlyEM7t6er3mMSCogHpO8FHRljmZZiOJJbRcaD6+L6tA/Tvs7M1sHdgTY8vOa2GDyU/w+shV3iwLw1WLXJDt7dmW0+K0b7I=
  - secure: nhQjenrseKFDQWyoqk3O5RmWzqrvZe6uvS4ScsprfsPJlXWK92GsWZJgK4dTkb6LxiVfITEhda4qeDZQuKEAtzTekeT5L76dXADT+2LnwtIbYINrIsS0VeZaCp/Df3TJdRIScVemfIHu15oaL+Ae2dmPOsmaw8ruhR9Sjv1Yd8sPdZcgkyEsFu9pOfAiuUQC9HPjtQRhS/xc1niBm727KjAF7CoMdQ682rs4+VvOsRC1y0bk3NcWeulHstzOZwpSSrEU4P4YDgWu3BtXTnh7M/sn+JX5xyL8SFCzUtRZcaPzqNnK/LZxOkrNlX8dU0o+i1e8bOuiJLPxbfNGKCvnjkDgJ9fyijmfJtOJ9hHqQbXszA1GVheGcIlBhKz0NRwbjrmLrTikV9ZYSZgVIzZMMunz1R/vCjTPBiV0mFgFAakpr8Kf620ATvv+w7dlf8Z5HJpFYgNB32MYjsfbom1ooyFCP833YN9lyR6CJiAb6rwjWHfqOpr98Kp1EhNLD0BmvzW+541iUdEah3ESMGn8VmlrabchYil8tmgf6kjcxfIsnMBCCBr4yJ6RlZpDY4rE4evn1zLsFD7A+7ehtnj97cqm+AgHFsH1ssYWNACrYqWQTL6UMp5mGy7tQA3GV8VlNq/K4mmpClV0fNvXIgp1uarRvpiVDWKBaoLNg0JUAZY=
  - secure: HJjWrbc8RXFupCPzKuBGq83xCb6rtHCvQqxH3mOVGLGi+ridVZljbgNS792O6qeJPvHsmYCzuwjBq1Azq2RMqbpx9L++DXO49FDUJobw70PSOLcwXuHaNVF49W7CUeWT+243APx3c/No1bn7jX+BZg66xh9S6+sMMbUA0LY0gj+oVl3p4ETlIvIrR82DXaZblkYhYikjZ8AAX1/Bhvk4cSGBSzP8biSLG+DlhuTNYRBOENJ0/30d/Oxhvp4wRtyxJ69dKjm5DKLEAxYqr25aPVb8ZZ8FexOMIp8EBYnoakpZ5zF3yidZ15jWHb8hJp9dgCZ3l5QXHWP24Ki/fS7pv7bJs7R7hGP67ry6xxwVE54P/GEafL20jszv1FzHduUCKwvvO+6FXINDDwHyBLOF4oJqFrW+MzdP5/NXq7moxrBTCO+Ce75CN8A5AJkyrWSFoXzy6mIMT/8JeXdjudbm03z746/MXYvKpo7zpVk9pSpGHxQuY0sGCT0fqMytObpymK+xkmeuOHYjqdwm2HPauFVwvyPKMBzcalr/iYF9m3IquBTsGGxzicjdULMwO6phgc9ZP+KSUMcwvuie34nZoj4TvB4eDyN+1Wi73n4j0NWsULXkCuurcIcHtbU6WKFpz+5kusnNGPmcVX+8J/AntSOC6RoZA3UeFOeEXT/glow=
  - secure: oW5PtGUWgiTGJq2KW3yuNuOufbQ9XmRES04RmJn2/sPYSPx+kXWE/pDx3sKBqMaPiXFXBaiJjiAOujO5p7kFW3rG1DpcKrOeXjRR9f85xm2F7YAFWKBUsc6qLusIjxpV1MgNrmV5PimheC9ifHZ0YR9XO/lDR9u9XoYj6JeuWRFpMZ1eJThwT6znrqDkM4b3UkSI82DYtwlvX6TaCyNLE9Y0IhyZ1ZLtg5o3HgyuPyR8Dy8+W/Q9+omB+m/fcxCDfYy9G/abf7W94Up/Kgp4PoK0k9XBD75y2OZ6bPEXvrhHYxBp93m2GO9pjlHlTINs2zHLTlVP2zW5J+jHRL0EG710MIr62Esw5M9M3REByUcRRYmviXr5TChTrvleJls/nEi82flDB8INt9U6Z1ABABi/IRNWhxKe0x9Pi4YoxkdjW8Dqzw28YmNGEcpADD7LTfO6K21uQEUhw25o7DyHaWBgnJlc9kXjEyesDgdDlaLPeWvnmWp8kEUYrQ/n/YPP6Q3UjpMaBodHfBGSizfSaavG9ClypDTTPLO36VRlZeJEQb7yXi2ExryCQxyMZSezk1+8YklZr4lLeUUhdrw5C/TsYIBvHcPLeO+73aW7xbq/130WHAUpCTMatUZeYRsWAxJwbXCPHSpOWnYvnxBXfHHXRj11z/AMoOdzSJZIO8w=
  - secure: WFp+G8Yi5kVjtu3S3K7BZHjrRSyv8qYv0p9ulLmasEz3ZF3H5QXM4XVGmoDvQgKvhEap74uBKb+ZZyaQjhWxzj3vWyUhUnr2w5mdr/8gWwywwXx+8XzBwAZp+bfHF83BQ0Kkyo8shF5UVH3ZpfTh3dFs5Bj+IhVQ7kXwMUExzfY0Zzo4mQjITMaIChRkLtJ7dk72mkcghMR/P3hjOUCfVqo+XhVgjtht4UPurUdWrkGxLSKuYI2A13LBi8Za06hbXEoP8tCoUfWu5pETK56YMvwsVjBKuYr27Dil9cH0QtNu+DxqbUvp6FQLGPG9iYUVTyeM3lBGE8dRXEz50l9YgMbdIyOTRRYIdwlCT8yglgpQQ3Jtkvg/gI7tuya1r8/eGbZWIQhUOWIRz1DS0HOBl9IjblGSnOpLrIol60qfVB1+z6mJ+DfCpWC/ULZVzy9YBP/K9RURSdMrb3LsinOg6b/EgmaxIiqx6TSHKtJ+dGzJ+a8Sl0BTG1ZTGr6ygzNG9tQd/m/bHv+TW5hqgfkfphp5Lg86EDoAjnYbe7aU3otIoxuaO3N/+6mWz+mUClvwrjWfAPf2lxENhzxyL38AuJc0RPdrwBPk5dsDJVFXKv+osocXDW1djtaNz1pMadSuMRc2QKFr6fTFsrbFYTBecx4AFB379xMqUEJDqF8XM+U=
  - secure: CZQrC8RHUa5ytNxtEtZvHDOieBGxZvBuSIxf3cF1H8Tyfd0VwGABE6MvTzZO77RsPkjSoz98HdudytCelNYiwGmQta0gbCpK1/8uaPNlCRFUK1Ruq0mCHfGRftckndfa3ZL6QAagjkZj3mK/RFrcN/k52XS9lz/rTi5l6WWaK9iXhx+mLNDnboQOF9rubKsLXx6YKCTkMLhRGatMJ9W91F/ysBKnvwGrM3kEBZBqCSYkuS58M1fWlllN17UNbRVhD21k2aweisfQGebowXE3XFOxW6Z62GoqyL5zVpeU+9Y7pKqkA05GyDclVZ98HGkBHYJkjzir0YYpkY8HK2+66yYD9Gsj8/dWOOfhiyTvSm/f7RUkM1Ao/K8XKeu6BHikZeacmIMr8MyheyqhGJd9YwITp6M43mBql/zUrTjJlyJY0QAbVV0SyOE3r6uMC6yaaK/N4Ng8aZYN1lg9mfZN6y9umdmkCgj67JbGPyrbnz+Di8t3zCwyU/KDsZrJssKfSqqUHb77Mh/FDRmFnfK0hJv3q36h2XAxbgVBmdx68N2bMpAXUMp8kz48Q5KRqkeJoUsVatCli5BUXdUXZ9a8bk4ROlN5FYonyGvrHo5kl6pnN616z3+gDnoQZ4ghIMOesEYZBmjgE0liLZs2hryh2OrvCKZwrjK5BJQl3K7SL+4=
